/* Copyright 2012 Aguzzi Cristiano

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package jada.ngeditor.guiviews;

import jada.ngeditor.guiviews.palettecomponents.*;

/**
 *
 * @author cris
 */
public class PaletteView extends javax.swing.JPanel {

    /**
     * Creates new form PaletteView
     */
    public PaletteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel1);
        addPaletteComponents();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addPaletteComponents(){
        try{
        NWidgetLayer layer    = new NWidgetLayer();
        NWidgetScreen screen  = new NWidgetScreen();
        NWidgetPanel panel    = new NWidgetPanel();
        NWidgetButton button  = new NWidgetButton();
        NWidgetTextField text = new NWidgetTextField();
   NWidgetCheck chek     = new NWidgetCheck();
   NWidgetLabel label    = new NWidgetLabel();
   NWidgetConsole cons   = new NWidgetConsole();
   NWidgetWindow  wind   = new NWidgetWindow();
   NWidgetRadioButton rbut = new NWidgetRadioButton();
   NWidgetImage     image = new NWidgetImage();
   NWidgetListBox   list = new NWidgetListBox();
   jPanel1.add(screen);
   jPanel1.add(layer);
   jPanel1.add(image);
   jPanel1.add(panel);
   jPanel1.add(label);
   jPanel1.add(button);
   jPanel1.add(text);
   jPanel1.add(chek);
   jPanel1.add(cons);
   jPanel1.add(wind);
   jPanel1.add(rbut);
   jPanel1.add(list);
    }catch (Exception e){}
    }
}
